# Generated by Django 4.2.7 on 2023-11-13 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("duck_code_editor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codesnippet",
            name="title",
        ),
    ]
