# Generated by Django 4.2.7 on 2023-11-20 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("duck_code_editor", "0006_remove_trial_task_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trial",
            name="survey_q1",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="trial",
            name="survey_q2",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="trial",
            name="survey_q3",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="trial",
            name="task_1",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_1",
                to="duck_code_editor.trial_task",
            ),
        ),
        migrations.AlterField(
            model_name="trial",
            name="task_1_duck",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_1_duck",
                to="duck_code_editor.trial_task",
            ),
        ),
        migrations.AlterField(
            model_name="trial",
            name="task_2",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_2",
                to="duck_code_editor.trial_task",
            ),
        ),
        migrations.AlterField(
            model_name="trial",
            name="task_2_duck",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_2_duck",
                to="duck_code_editor.trial_task",
            ),
        ),
        migrations.AlterField(
            model_name="trial",
            name="test_task",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_task",
                to="duck_code_editor.trial_task",
            ),
        ),
    ]
