# Generated by Django 4.2.7 on 2023-11-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "duck_code_editor",
            "0007_alter_trial_survey_q1_alter_trial_survey_q2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trial_task",
            name="familiarity",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial_task",
            name="silence",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial_task",
            name="talking",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
