# Generated by Django 4.2.7 on 2023-11-27 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("duck_code_editor", "0008_trial_task_familiarity_trial_task_silence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trial",
            name="task_3",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_3",
                to="duck_code_editor.trial_task",
            ),
        ),
        migrations.AddField(
            model_name="trial",
            name="task_3_duck",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_3_duck",
                to="duck_code_editor.trial_task",
            ),
        ),
    ]
