# Generated by Django 4.2.7 on 2023-11-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duck_code_editor", "0009_trial_task_3_trial_task_3_duck"),
    ]

    operations = [
        migrations.AddField(
            model_name="trial",
            name="big_five_q1",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="big_five_q10",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="big_five_q2",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="big_five_q3",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="big_five_q4",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="big_five_q5",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="big_five_q6",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="big_five_q7",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="big_five_q8",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="big_five_q9",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="percpetion_q1",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="percpetion_q2",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="percpetion_q3",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="percpetion_q4",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="percpetion_q5",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="percpetion_q6",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="percpetion_q7",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
