# Generated by Django 4.2.7 on 2023-11-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duck_code_editor", "0011_rename_percpetion_q1_trial_perception_q1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trial",
            name="survey_q3",
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
