# Generated by Django 4.2.7 on 2023-11-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duck_code_editor", "0012_alter_trial_survey_q3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trial",
            name="survey_q3",
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
    ]
