# Generated by Django 4.2.7 on 2023-11-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duck_code_editor", "0004_remove_trial_task_trial_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trial_task",
            name="duration",
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="trial_task",
            name="end_time",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
